using System;
using System.Collections.Generic;
using System.Linq;

namespace Jablotron.API.SIA.Models
{
    public static class SiaEventCodeCatalog
    {
        private static readonly Dictionary<string, IReadOnlyList<string>> ByCode =
            new(StringComparer.OrdinalIgnoreCase)
            {
                ["AR"] = new[] { "AC Restoral" },
                ["AT"] = new[] { "AC Trouble" },
                ["BA"] = new[] { "Burglary Alarm" },
                ["BR"] = new[] { "Burglary Restoral" },
                ["BV"] = new[] { "Burglary Verified" },
                ["BX"] = new[] { "Burglary Test" },
                ["CD"] = new[] { "Closing Delinquent" },
                ["CF"] = new[] { "Forced Closing" },
                ["CG"] = new[] { "Close Area" },
                ["CI"] = new[] { "Fail To Close" },
                ["CK"] = new[] { "Early To Close" },
                ["CL"] = new[] { "Closing Report" },
                ["CP"] = new[] { "Automatic Closing" },
                ["CQ"] = new[] { "Remote Closing" },
                ["CS"] = new[] { "Closing Keyswitch" },
                ["CT"] = new[] { "Late To Open" },
                ["DC"] = new[] { "Access Closed" },
                ["DD"] = new[] { "Access Denied" },
                ["DF"] = new[] { "Door Forced" },
                ["DG"] = new[] { "Access Granted" },
                ["DI"] = new[] { "Access Denied Passback" },
                ["DN"] = new[] { "Door Left Open" },
                ["DO"] = new[] { "Access Open" },
                ["DR"] = new[] { "Door Restoral" },
                ["DX"] = new[] { "Request To Exit" },
                ["EA"] = new[] { "Exit Alarm" },
                ["EJ"] = new[] { "Expansion Tamper Restore" },
                ["EM"] = new[] { "Expansion Missing" },
                ["EN"] = new[] { "Expansion Missing Restore" },
                ["ER"] = new[] { "Expansion Restoral" },
                ["ES"] = new[] { "Expansion Device Tamper" },
                ["ET"] = new[] { "Expansion Trouble" },
                ["FA"] = new[] { "Fire Alarm", "Enet Fire Alarm" },
                ["FB"] = new[] { "Fire Bypass" },
                ["FC"] = new[] { "Fire Cancel" },
                ["FJ"] = new[] { "Fire Trouble Restore" },
                ["FR"] = new[] { "Fire Restoral", "Enet Fire Restoral" },
                ["FT"] = new[] { "Fire Trouble" },
                ["FU"] = new[] { "Fire Unbypass" },
                ["HA"] = new[] { "Holdup Alarm", "User Duress", "MDT Belt Clip", "RPA Holdup" },
                ["HB"] = new[] { "Holdup Bypass" },
                ["HJ"] = new[] { "Holdup Trouble Restore" },
                ["HR"] = new[] { "Holdup Restoral", "User Duress Restore", "MDT Belt Clip Restore", "RPA Holdup Restore" },
                ["HT"] = new[] { "Holdup Trouble" },
                ["HU"] = new[] { "Holdup Unbypass" },
                ["HV"] = new[] { "Confirmed Holdup" },
                ["JA"] = new[] { "User Code Tamper Web Or XBUS" },
                ["JP"] = new[] { "User Accessing" },
                ["JT"] = new[] { "Time Changed" },
                ["JV"] = new[] { "User Code Change" },
                ["LB"] = new[] { "Local Programming" },
                ["LR"] = new[] { "Modem Restoral" },
                ["LT"] = new[] { "Modem Trouble" },
                ["LX"] = new[] { "Local Programming Ended" },
                ["MA"] = new[] { "Medical Alarm", "Enet Medical Alarm", "MDT Tilt" },
                ["MB"] = new[] { "Medical Bypass" },
                ["MJ"] = new[] { "Medical Trouble Restore" },
                ["MR"] = new[] { "Medical Restoral", "Enet Medical Restoral", "MDT Tilt Restore" },
                ["MT"] = new[] { "Medical Trouble" },
                ["MU"] = new[] { "Medical Unbypass" },
                ["NB"] = new[] { "Xbus Alert Close" },
                ["NL"] = new[] { "Perimeter Armed" },
                ["NO"] = new[] { "Xbus Alert Reopen" },
                ["NR"] = new[] { "Network Link Restore" },
                ["NT"] = new[] { "Network Link Fail" },
                ["OA"] = new[] { "Automatic Opening" },
                ["OG"] = new[] { "Open Area" },
                ["OK"] = new[] { "Early Open" },
                ["OP"] = new[] { "Opening Report" },
                ["OQ"] = new[] { "Remote Opening" },
                ["OR"] = new[] { "Disarm From Alarm" },
                ["OS"] = new[] { "Opening Keyswitch" },
                ["OT"] = new[] { "Late To Close" },
                ["PA"] = new[] { "Panic Alarm", "Enet Panic Alarm", "User Panic Alarm", "MDT Panic", "RPA Panic" },
                ["PB"] = new[] { "Panic Bypass" },
                ["PJ"] = new[] { "Panic Trouble Restore" },
                ["PR"] = new[] { "Panic Restoral", "Enet Panic Restoral", "MDT Panic Restore", "RPA Panic Restore" },
                ["PT"] = new[] { "Panic Trouble" },
                ["PU"] = new[] { "Panic Unbypass" },
                ["RC"] = new[] { "Relay Close" },
                ["RN"] = new[] { "Remote Reset" },
                ["RO"] = new[] { "Relay Open" },
                ["RP"] = new[] { "Automatic Test" },
                ["RR"] = new[] { "Powerup" },
                ["RS"] = new[] { "Remote Program Success" },
                ["RT"] = new[] { "Remote Program Unsuccessful" },
                ["RX"] = new[] { "Manual Test" },
                ["SD"] = new[] { "Alert Close" },
                ["SO"] = new[] { "Alert Reopen" },
                ["TC"] = new[] { "Walktest End" },
                ["TP"] = new[] { "Zone Walked" },
                ["TR"] = new[] { "Trouble Restoral" },
                ["TS"] = new[] { "Trouble Silence" },
                ["TT"] = new[] { "Trouble" },
                ["TU"] = new[] { "Trouble Unbypass" },
                ["UA"] = new[] { "Untyped Zone Alarm" },
                ["UR"] = new[] { "Untyped Zone Restoral" },
                ["US"] = new[] { "Untyped Zone Supervision Trouble" },
                ["UT"] = new[] { "Untyped Zone Trouble" },
                ["UU"] = new[] { "Untyped Zone Unbypass" },
                ["UY"] = new[] { "Untyped Zone Missing" },
                ["UZ"] = new[] { "Untyped Zone Missing Restore" },
                ["WA"] = new[] { "Water Alarm" },
                ["WB"] = new[] { "Water Bypass" },
                ["WJ"] = new[] { "Water Trouble Restore" },
                ["WR"] = new[] { "Water Restoral" },
                ["WS"] = new[] { "Water Flow" },
                ["WT"] = new[] { "Water Trouble" },
                ["WU"] = new[] { "Water Unbypass" },
                ["WW"] = new[] { "Locked Out" },
                ["XD"] = new[] { "Low Voltage" },
                ["XG"] = new[] { "Low Voltage Restoral" },
                ["XK"] = new[] { "Deep Charge" },
                ["XT"] = new[] { "Zone Low Battery" },
                ["XR"] = new[] { "Zone Low Battery Restoral" },
                ["YA"] = new[] { "Bell Trouble" },
                ["YB"] = new[] { "Battery Missing" },
                ["YC"] = new[] { "Communication Trouble" },
                ["YD"] = new[] { "PSU Trouble" },
                ["YE"] = new[] { "Battery Trouble" },
                ["YF"] = new[] { "Service Required" },
                ["YG"] = new[] { "Watchdog Reset" },
                ["YH"] = new[] { "Bell Restored" },
                ["YK"] = new[] { "Communication Restoral" },
                ["YM"] = new[] { "Battery Missing" },
                ["YP"] = new[] { "PSU Trouble" },
                ["YQ"] = new[] { "PSU Restoral" },
                ["YR"] = new[] { "Battery Restoral" },
                ["YS"] = new[] { "Communication Trouble" },
                ["YT"] = new[] { "Battery Trouble" },
                ["YW"] = new[] { "Watchdog Reset" },
                ["YX"] = new[] { "Service Required" },
                ["YZ"] = new[] { "Service Completed" },
                ["ZA"] = new[] { "Freeze Alarm" },
                ["ZR"] = new[] { "Freeze Restoral" },
                ["ZG"] = new[] { "User Accessing End" },
                ["ZC"] = new[] { "Zone Close" },
                ["ZD"] = new[] { "Zone Disconnect" },
                ["ZK"] = new[] { "Walktest Start" },
                ["ZM"] = new[] { "Zone Masked" },
                ["ZO"] = new[] { "Zone Open" },
                ["ZX"] = new[] { "Zone Short" },
                ["AU"] = new[] { "Unknown Card" },
                ["CU"] = new[] { "Camera Online" },
                ["CV"] = new[] { "Camera Offline" },
                ["nan"] = new[] { "Code Deleted" }
            };

        public static IReadOnlyList<string> FindDescriptions(string code)
        {
            if (string.IsNullOrWhiteSpace(code))
                return Array.Empty<string>();

            if (ByCode.TryGetValue(code.Trim(), out var direct))
                return direct;

            var key = new string(code.Where(c => !char.IsDigit(c)).ToArray());
            if (ByCode.TryGetValue(key, out var normalized))
                return normalized;

            return Array.Empty<string>();
        }
    }
}
